theme: jekyll-theme-cayman
title: DISCOVERY Stake Pools
github:
  is_project_page: no
  Telegram: https://t.me/bumpydetour
  Adapools: https://adapools.org/pool/654d96593e499e70889eeae16a15ad8682f8349fd1b77726bbbf8a6d
